### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by BrockSmedley** [nicolasgarnier/drive-music-player#37] opened 2015-02-03 21:39 UTC
Time elapsed is the same as total time. Thusly, the progress bar is always at 100%.

**Comment by nicolasgarnier** [comment] 2015-07-01 08:15
Hey @BrockSmedley, Could you please tell me what browser you are using? it seems that this issue is affecting Firefox users. Anyways after investigation it seems that the bug is due to an issue with how Google Drive serves the files (a missing HTTP header). Nothing I can fix on my end unfortunately but I've sent a bug report to the Google Drive team.

Also this is a duplicate of #31 Lets use #31 to track this issue.

**Closed by nicolasgarnier** 2015-07-01 08:15 UTC
