### ISSUE TITLE
Multiple selection bug

### ISSUE THREAD

**Issue by Javimetal82** [nicolasgarnier/drive-music-player#66] opened 2015-05-29 17:21 UTC
Hi,
Just to let you know about a bug that shows when one tries to play a multiple selection of audio files from Google Drive. 
The Music Player displays the following message: "Your playlist is empty. Add some music".
You have to go back and try again selecting the files, and then the player recognizes them.
Thanks in advance for your concern.
Best regards.

**Comment by nicolasgarnier** [comment] 2015-06-25 21:44
Thanks for the report. I just pushed a new version with a bunch of bug fixes. It seems that this is working fine now so I am closing this issue. Please let me though if the issue is still happening for you.

**Closed by nicolasgarnier** 2015-06-25 21:44 UTC
